wordpress:
  image: wordpress
  container_name: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
  environment:
      WORDPRESS_DB_PASSWORD: Passw0rd

wordpress_db:
  image: mysql:5.7
  container_name: mysql
  environment:
      MYSQL_ROOT_PASSWORD: Passw0rd

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: Passw0rd
